export const GET_VOUCHER = 'GET_VOUCHER';
export const GET_VOUCHERS = 'GET_VOUCHERS';
export const GET_VOUCHERS_SUCCESS = 'GET_VOUCHERS_SUCCESS';
export const GET_VOUCHERS_FAILURE = 'GET_VOUCHERS_FAILURE';
export const CREATE_VOUCHER= 'CREATE_VOUCHER';
export const CREATE_VOUCHER_SUCCESS= 'CREATE_VOUCHER_SUCCESS';
export const CREATE_VOUCHER_FAILURE= 'CREATE_VOUCHER_FAILURE';
export const DISABLE_VOUCHER = "DISABLE_VOUCHER";
export const DISABLE_VOUCHER_SUCCESS = "DISABLE_VOUCHER_SUCCESS";
export const DISABLE_VOUCHERS_FAILURE = "DISABLE_VOUCHERS_FAILURE";
export const UPDATE_VOUCHER = "UPDATE_VOUCHER";
export const UPDATE_VOUCHER_SUCCESS = "UPDATE_VOUCHER_SUCCESS";
export const UPDATE_VOUCHER_FAILURE = "UPDATE_VOUCHER_FAILURE";
export const UPDATE_VOUCHERS = "UPDATE_VOUCHERS";
export const GET_SINGLE_VOUCHER = "GET_SINGLE_VOUCHER";
export const GET_SINGLE_VOUCHER_SUCCESS = "GET_SINGLE_VOUCHER_SUCCESS";
export const GET_SINGLE_VOUCHER_FAILURE = "GET_SINGLE_VOUCHER_FAILURE";
export const GET_GENERATE_CSV = "GET_GENERATE_CSV";
export const GET_GENERATE_CSV_SUCCESS = "GET_GENERATE_CSV_SUCCESS";
export const GET_GENERATE_CSV_FAILURE = "GET_GENERATE_CSV_FAILURE";

export const UPDATE_VOUCHER_BY_AMOUNT = "UPDATE_VOUCHER_BY_AMOUNT";
export const UPDATE_VOUCHER_BY_AMOUNT_SUCCESS = "UPDATE_VOUCHER_BY_AMOUNT";
export const UPDATE_VOUCHER_BY_AMOUNT_FAILURE = "UPDATE_VOUCHER_BY_AMOUNT_FAILURE";

export const UPDATE_VOUCHER_BY_EXPIRYDATE = "UPDATE_VOUCHER_BY_EXPIRYDATE";
export const UPDATE_VOUCHER_BY_EXPIRYDATE_SUCCESS = "UPDATE_VOUCHER_BY_EXPIRYDATE";
export const UPDATE_VOUCHER_BY_EXPIRYDATE_FAILURE = "UPDATE_VOUCHER_BY_EXPIRYDATE_FAILURE";

export const GET_DISCOUNT_VOUCHERS = "GET_DISCOUNT_VOUCHERS";
export const GET_DISCOUNT_VOUCHERS_SUCCESS = "GET_DISCOUNT_VOUCHERS_SUCCESS";
export const GET_DISCOUNT_VOUCHERS_FAILURE = "GET_DISCOUNT_VOUCHERS_FAILURE";

export const REDEEM_VOUCHER = "REDEEM_VOUCHER";
export const REDEEM_VOUCHER_SUCCESS = "REDEEM_VOUCHER_SUCCESS";
export const REDEEM_VOUCHER_FAILURE = "REDEEM_VOUCHER_FAILURE";